#.travis.yml

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run start:once

after_success:
  - cat ./coverage/*/lcovonly | ./node_modules/coveralls/bin/coveralls.js