#.travis.yml

language: node_js
node_js:
  - "6"

addons:
  chrome: stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

script:
  - ng lint
  - ng test -sr -cc

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info